parameters:
#    best_deal_commande.example.class: BestDeal\CommandeBundle\Example

services:
#    best_deal_commande.example:
#        class: %best_deal_commande.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
