parameters:
#    best_deal_livraison.example.class: BestDeal\LivraisonBundle\Example

services:
#    best_deal_livraison.example:
#        class: %best_deal_livraison.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
