parameters:
#    best_deal_reclamation.example.class: BestDeal\ReclamationBundle\Example

services:
#    best_deal_reclamation.example:
#        class: %best_deal_reclamation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
