parameters:
#    best_deal_client.example.class: BestDeal\ClientBundle\Example

services:
#    best_deal_client.example:
#        class: %best_deal_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
