best_deal_reclamation:
    resource: "@BestDealReclamationBundle/Resources/config/routing.yml"
    prefix:   /rec
best_deal_commande:
    resource: "@BestDealCommandeBundle/Resources/config/routing.yml"
    prefix:   /
best_deal_livraison:
    resource: "@BestDealLivraisonBundle/Resources/config/routing.yml"
    prefix: /
best_deal_client:
    resource: "@BestDealClientBundle/Resources/config/routing.yml"
    prefix:   /
best_deal_article:
    resource: "@BestDealArticleBundle/Resources/config/routing.yml"
    prefix:   /

best_deal_main:
    resource: "@BestDealMainBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    


