parameters:
#    best_deal_main.example.class: BestDeal\MainBundle\Example

services:
#    best_deal_main.example:
#        class: %best_deal_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
